# Generated by Django 4.2.16 on 2024-10-08 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('fiction', 'Fiction'), ('non_fiction', 'Non-Fiction'), ('mystery', 'Mystery'), ('fantasy', 'Fantasy'), ('biography', 'Biography'), ('history', 'History'), ('science', 'Science'), ('romance', 'Romance'), ('others', 'Others')], max_length=20),
        ),
    ]
